language: generic
sudo: required
services:
    - docker
    
before_install:
    - docker build -t davidsevier/docker-react -f Dockerfile.dev .
        
script:
    - docker run -e CI=true davidsevier/docker-react npm run test